[project]
name = "babies-tracking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dash-bootstrap-components>=1.7.1",
    "duckdb>=1.2.0",
    "gunicorn>=23.0.0",
    "pandas>=2.2.3",
]
